### ISSUE TITLE
Exemplify boolean evaluation of filter expression

### ISSUE THREAD

**Issue by nichtich** [deutsche-nationalbibliothek/pica-rs#458]
The documentation of `filter` says:

> Boolean expressions are evaluated lazy from left to right.

This should better be exemplified. Is `A && B || C` evaluated as `(A && B) || C` and  `A || B && C` as `(A || B) && C`?

**Comment by niko2342** [comment]
Given an expression "A || B". Lazy evaluation means that if "A" is true "B" wont be evaluated, because it's not necessary. The complete expression evaluates to true. Same for expressions including the boolean AND connective, if A is false the complete expression is false and B wont be evaluated.

The precedence of the AND-Operator is higher than the OR-Operator. Therefore, the expression "A || B && C" is equivalent to "A || (B && C)".

Im going to improve the documentation and add some examples.
