### ISSUE TITLE
Stabilize `sample` command

### ISSUE THREAD

**Issue by nwagner84** [deutsche-nationalbibliothek/pica-rs#514]
Tracking issue for stabilizing the `sample` command.

## Features

- [x] #564 

## Documentation

- [x] Add/Review CLI documentation (note reservoir sampling)

## Internals

- [x] Add snapshot tests

**Comment by nichtich** [comment]
I guess the command uses [reservoir sampling](https://en.wikipedia.org/wiki/Reservoir_sampling) (otherwise we could simply use [shuf](https://linux.die.net/man/1/shuf) instead) so this should be documented, e.g.

> The sample command selects a random permutation of records of the given sample size using [reservoir sampling](https://en.wikipedia.org/wiki/Reservoir_sampling).

**Comment by niko2342** [comment]
Yes, the `sample` command uses reservoir sampling and it's very important to document this fact, because of the drawbacks of this sampling method. I will document this fact and a note about the drawbacks; as well as an alternative way using `shuf`.

NB: The `shuf` command is not able to skip invalid records and to automatically decompress a `.gz` dump. Therfore, a combination of `pica cat -s DUMP.dat | shuf` or `shuf DUMP.dat | pica cat -s` or  `zcat DUMP.dat.gz | shuf | pica cat -s` is necessary. The `sample` command is just a convenient way to combine this into a single command if reservoir sampling is sufficient.
