### ISSUE TITLE
Stabilize `slice` command

### ISSUE THREAD

**Issue by niko2342** [deutsche-nationalbibliothek/pica-rs#517]
Tracking issue for stabilizing the `slice` command.

## Features

_n/a_

## Documentation

- [ ] Add/Review CLI documentation

## Internals

- [ ] Update to new `pica-record` crate
- [ ] Add snapshot tests

**Comment by nichtich** [comment]
Two notes about changes in documentation and two about changes/additions in functionality:

1. Common use case is to get the first *n* records, this can also be done with `head`:

~~~
$ pica $CMD file.dat | head -n 5  # get first 5 records of result
$ head -5 file.dat | pica $CMD # process first 5 record lines (may be less with --skip-invalid)
~~~

I'd always prefer `head` and `tail` unless `pica slice` works the same way:

~~~
$ pica slice -n 5 file.dat  # at least this should be supported
~~~

2. Documentation says the default of `start`, `end`, `length` is `0` but the example seems to use record counting start at 1, better adjust the example to not start with 1. Zero-based counting is confusing anyway, see also below.

~~~
# get records at position 1, 2 or 3 (without invalid record)
$ pica slice --skip-invalid --start 1 --end 4 -o slice.dat DUMP.dat
~~~

This will print less then 3 records if some of the three are invalid? This should better be documented, e.g. "invalid records are counted, but not returned with option `--skip-invalid`".

3. Zero-based counting for "start" and "end" and mathematical terms like "lower bound" can be confusing. Better document this way:

- `--start $n` skip the first `$n` input records
- `--end $n` stop after `$n` input records

4. Default values for `length` and `end` are `0` but this should result in zero results! Better not use this default values and support `0` as normal number instead of placeholder for undefined.

**Comment by nichtich** [comment]
Options `--start`, `-n, --end`, `--length` should be available at most other commands with same semantics as well, e.g. `print`.

**Comment by niko2342** [comment]
I completely disagree, that this options should be supported by most other command. This would result in an increased complexity of other commands as well as the risk in naming conflicts of command-line options.

The semantic of the `--limit` and `--end` options are different: Limit stops after processing *x* valid records, whereas `--end` indicate the end of the slice. If a limit value is between start and end, the slice would be incomplete. Same problem exists for `length`. Your change would introduce a second semantic of the `--limit` option for this command (the meaning of the former option `--length`), which is, at least for me, not stringent across the other commands.

If there is a real use case for the `--limit` option (stop, after reading *x* valid records) to this command, we can **add** this option without changing the existing ones.

Regarding your first comment, if you more familiar with `head` and `tail` you should use it! I encourage pica-rs users, to use pica-rs only when it makes sense and when it fits into existing workflows. If pica-rs is used as a pre-processing step for metafacture or picadata, it's fine. If the sampling method of the `sample` command is not good enough, just use `shuf`. It's part of the project philosophy, that the whole range of linux  command-line tools can be combined through pipes with the command. And some of the pica-rs command, like `slice`, are very similar to existing tools, but have the advantage to skip invalid records or read gzip files.

It is very important to improve the documentation; this is an ongoing task and I have to ask for patience. My working 
 time, which I can spent into this project, is very limited. Most of the work is done in my free time and then I would like to focus on interesting programming task rather than improving the documentation. I'll check the documentation and clarify the points you mentioned during the command stabilization phase.
